### ISSUE TITLE
Approval System

### ISSUE THREAD

**Issue by crazyRM** [Jexactyl/Jexactyl#93]
### Current Behavior

even if the approval system is off it still need them to to be aproved

### Expected Behavior

they should not need to be approved

### Steps to Reproduce

idk

### Panel Version

latest

### Wings Version

latest

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Fixed in v3.4.2

**Comment by AndyIsHereBoi** [comment]
I partially have this issue, the users still show up in the approval menu even if it is disabled. This does not effect the user at all. They only show up in that menu but can still access everything.
